name: Bluefin GTS ISO Build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * sun'  # 02:00 Sunday
 

jobs:
  build-gts:
    name: Bluefin GTS
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/reusable-build-iso.yml
    secrets: inherit
    with:
      brand_name: bluefin
      fedora_version: 39
